### ISSUE TITLE
api: '21' what does it mean ?

### ISSUE THREAD

**Issue by hannesa2** [ravinderjangra/android-ndk-toolchain-setup#2]
Sorry, I didn't looked into the code, when I specify 

```
with: 
    api: '21'
```

does it mean I specify NDK version in `build.gradle` like

```
android {
   ...
   ndkVersion '21.0.6113669'
}
```
and can use NDK `21.0.6113669` ?

Or is it the Emulator version ?  (I guess not)

Btw, the `README.md` is a little bit rudimentary and wrong

**Comment by ravinderjangra** [comment]
it's the Android API version against which the code will be compiled. Currently, the action always uses the available NDK version from the GHA pool. 

You can find the software/sdk versions for all the GHA pool images here: https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners.
