### ISSUE TITLE
Action not found

### ISSUE THREAD

**Issue by benalexau** [ravinderjangra/android-ndk-toolchain-setup#35]
I am attempting to try this action to setup NDK as follows:

```yaml
    - name: Install Android NDK Toolchain
      uses: actions/android-ndk-toolchain-setup@v0.1
      if: runner.os == 'Linux'
      with: 
        arch: 'x86'
        install-location: 'toolchains'
```

This results in error:

```
##[warning]Failed to download action 'https://api.github.com/repos/actions/android-ndk-toolchain-setup/tarball/v0.1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 12.498 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/actions/android-ndk-toolchain-setup/tarball/v0.1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 28.368 seconds before retry.
##[error]Response status code does not indicate success: 404 (Not Found).
```

As suggested in #1 I tried using `uses: ravinderjangra/android-ndk-toolchain-setup@0.1`, but it gave the same error. I noticed this is also being used in [your workflow](https://github.com/ravinderjangra/AndroidResumeIssue/blob/master/.github/workflows/main.yml).

Can you please clarify?

**Comment by ravinderjangra** [comment]
you may have to create a directory to store the toolchain and pass that to the action using install-location parameter. 
` install-location: 'toolchains'`

**Comment by ravinderjangra** [comment]
I will try to include a note to update the README and GitHub actions to correct this ASAP.

**Comment by benalexau** [comment]
Thanks for your fast reply.

Upon further investigation it turns out the Ubuntu virtual environment makes an NDK available at `$ANDROID_SDK_ROOT/ndk-bundle`. As such I won't need to install it separately. Thanks again.

**Comment by ravinderjangra** [comment]
Glad to know, you were able to resolve the issue in your setup. Just FYI @benalexau, this action is to create a build toolchain using the NDK but not to install the NDK. I myself is using the already installed NDK from the system.
