### ISSUE TITLE
Make it work in macOS

### ISSUE THREAD

**Issue by hannesa2** [ravinderjangra/android-ndk-toolchain-setup#37]
https://github.com/ravinderjangra/android-ndk-toolchain-setup/blob/8cbc7305ba08258a142a7b66d2b516f716dfabb5/src/ndk.ts#L6

On macOS I found it here. But there can be more then one !
```
# find . -name make*.py
./sdk/ndk/21.0.6113669/build/tools/make_standalone_toolchain.py
```

I've no skills in Python, so I don't know how to make it work in Python.
In shell I would to

`$(find $ANDROID_HOME/build-tools -name make_standalone_toolchain.py | sort | tail -1)`
(= Search for all available, sort by most recent and take first)

**Comment by hannesa2** [comment]
What can I do, to help you to make it work ?

**Comment by ravinderjangra** [comment]
I think we need to update `ndk.ts` file to add something like the following. Though I'll have to check the TS syntax.

```
import * as os from 'os'

export class Ndk {
const osPlatform = os.platform()

private static defaultNDKPath: string = ""

if (osPlatform == 'linux)
  defaultNdkPath =
    '/usr/local/lib/android/sdk/ndk-bundle/build/tools/make_standalone_toolchain.py'
else if (osPlatform == 'darwin')
  defaultNdkPath =
    'MACOS_NDK_DEFAULT_LOCATION'
}
```

**Comment by hannesa2** [comment]
Hm, how to specify right `MACOS_NDK_DEFAULT_LOCATION` ?

I found this ones

<img width="834" alt="image" src="https://user-images.githubusercontent.com/3314607/79872303-eb7feb80-83e5-11ea-8857-2dbbe62f1066.png">

I'll start with the last one

**Comment by ravinderjangra** [comment]
@hannesa2 would you like to review https://github.com/ravinderjangra/android-ndk-toolchain-setup/pull/43?
