### ISSUE TITLE
Can't use selected NDK 21, it's still 18

### ISSUE THREAD

**Issue by hannesa2** [ravinderjangra/android-ndk-toolchain-setup#45]
Using v2 and use NDK `21`

https://github.com/hannesa2/CVScanner/pull/20/files#diff-508ed730a77db23e1d8deff889f9fe6bR33-R41
<img width="410" alt="image" src="https://user-images.githubusercontent.com/3314607/79949729-4a8d4100-8476-11ea-9f69-32619b84b5e2.png">

does not take use of it
https://github.com/hannesa2/CVScanner/pull/20/checks?check_run_id=607611274

<img width="912" alt="image" src="https://user-images.githubusercontent.com/3314607/79949517-faae7a00-8475-11ea-844c-65f2cc5255e5.png">

It's still NDK `18`

**Comment by ravinderjangra** [comment]
21 is the Android API version and latest version of NDK is 18. so there no issue with the setup.

**Comment by hannesa2** [comment]
Ok, then I missed something complete.

> and latest version of NDK is 18

NDK latest is 21 ! https://developer.android.com/ndk/downloads/

The name is _android-**ndk**-toolchain-setup_, and specify `api: 21` means Andorid API 21 not NDK ! _Is this really right_ ?

If this is right, the name is complete misleading because I want to specify 
NDK version and not Android version

I'm not sure, who is wrong here 


Or may be this option is definitely missing 
`ndk: 21.0.6113669`

**Comment by ravinderjangra** [comment]
If you check the last statement in the screenshot it says the latest version available is 18.somethings. we can include the option to use a custom version of the NDK, in that case we may have to update the action to download the specific version based on the user input.

>The name is android-ndk-toolchain-setup, and specify api: 21 means Andorid API 21 not NDK ! Is this really right?

This GHA is to generate the toolchain which depends on the Android API version and then used to compile the native code and generate native libs using that specific API version.

**Comment by hannesa2** [comment]
> If you check the last statement in the screenshot it says the latest version available is 18.somethings. 

Not exactly, it's **locally available**. 
This is my primary goal, to change this, to an other (more modern) version 

> we can include the option to use a custom version of the NDK, in that case we may have to update the action to download the specific version based on the user input.

YES, please ! ❤️
